#version: '3.6'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_HOST: postgres
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/data/postgresql.db

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres